### ISSUE TITLE
Starboard on embeds 

### ISSUE THREAD

**Issue by NotSoMik** [eNtee-bots/discord-starboard#1]
Hello, if I put a star on an embed the bot will not send the starboard message. Did it work for you?

**Comment by fb-sean** [comment]
That this could be because of multiple reasons.
1. The code is for Djs v13
2. Do you have the right intents?
3. Does it log any error? 
4. Did you already logged the } catch { [here](https://github.com/fb-sean/discord-starboard/blob/main/starboardEvent.js#L159)?

The code at all is really outdated and I also dont use it anymore at my bots. I will not update this repo cuz I dont see a reason for this.

**Comment by NotSoMik** [comment]
About the intents Im using guilds, guilds messages and guild message reactions, when yoj tested it it worked on embeds?

**Comment by fb-sean** [comment]
I tested this 10 months ago and it worked yes.

**Comment by NotSoMik** [comment]
Oh ok, I'll log that error

**Comment by NotSoMik** [comment]
I got this error https://sourceb.in/BPA87aCU6d and it redirects me [here](https://github.com/fb-sean/discord-starboard/blob/main/starboardEvent.js#L131)

**Comment by fb-sean** [comment]
I already told you that this code is for discord.js v13 and you use v14..
To fix this issue you need to add a "if" that checks if there is really a message content.

**Comment by NotSoMik** [comment]
All right, just to be sure I will also test it on v13

**Comment by fb-sean** [comment]
Don't forget that you still need to add this if.. else it will still dont work without any problems

**Comment by NotSoMik** [comment]
Oh ok, thanks

**Comment by NotSoMik** [comment]
Hello, I just found out that custom emojis wont work only the default ones by discord is there a way to avoid this

**Comment by fb-sean** [comment]
Yeah code it.

**Comment by NotSoMik** [comment]
very helpful
